package io.github.seanboyy.matmod.items;

import net.minecraft.init.SoundEvents;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.registry.ForgeRegistries;

public final class ModItems {
	
	public static Item upgradedDiamondPickaxe;
	public static Item upgradedDiamondAxe;
	public static Item upgradedDiamondHoe;
	public static Item upgradedDiamondShovel;
	public static Item upgradedDiamondSword;
	public static Item emeraldPickaxe;
	public static Item emeraldAxe;
	public static Item emeraldHoe;
	public static Item emeraldShovel;
	public static Item emeraldSword;
	public static Item obsidianPickaxe;
	public static Item obsidianAxe;
	public static Item obsidianHoe;
	public static Item obsidianShovel;
	public static Item obsidianSword;
	public static Item hybridPickaxe;
	public static Item hybridAxe;
	public static Item hybridHoe;
	public static Item hybridShovel;
	public static Item hybridSword;
	public static Item upgradedDiamond;
	public static Item hybridMix;
	public static Item hybridIngot;
	public static Item ironRod;
	public static Item diamondRod;
	public static Item obsidianRod;
	public static Item obsidianIngot;
	public static Item upgradedDiamondHelmet;
	public static Item upgradedDiamondChestplate;
	public static Item upgradedDiamondLeggings;
	public static Item upgradedDiamondBoots;
	public static Item emeraldHelmet;
	public static Item emeraldChestplate;
	public static Item emeraldLeggings;
	public static Item emeraldBoots;
	public static Item obsidianHelmet;
	public static Item obsidianChestplate;
	public static Item obsidianLeggings;
	public static Item obsidianBoots;
	public static Item hybridHelmet;
	public static Item hybridChestplate;
	public static Item hybridLeggings;
	public static Item hybridBoots;
	
	public static ToolMaterial UPGRADED_DIAMOND = EnumHelper.addToolMaterial("UPGRADED_DIAMOND", 3, 2250, 10.0F, 4.5F, 15);
	public static ToolMaterial EMERALD = EnumHelper.addToolMaterial("EMERALD", 3, 2000, 11.0F, 5.0F, 15);
	public static ToolMaterial OBSIDIAN = EnumHelper.addToolMaterial("OBSIDIAN", 3, 3500, 12.0F, 6.0F, 13);
	public static ToolMaterial HYBRID = EnumHelper.addToolMaterial("HYBRID", 4, 5000, 16.0F, 7.0F, 20);
	
	public static ArmorMaterial UPGRADED_DIAMONDA = EnumHelper.addArmorMaterial("UPGRADED_DIAMOND", "matmod:upgraded_diamond_armor", 38, new int[] {3,8,6,3}, 15, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
	public static ArmorMaterial EMERALDA = EnumHelper.addArmorMaterial("EMERALD", "matmod:emerald_armor", 40, new int[] {3,8,6,3}, 20, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 2.5F);
	public static ArmorMaterial OBSIDIANA = EnumHelper.addArmorMaterial("OBSIDIAN", "matmod:obsidian_armor", 43, new int[] {3,8,6,3}, 18, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 3.0F);
	public static ArmorMaterial HYBRIDA = EnumHelper.addArmorMaterial("HYBRID", "matmod:hybrid_armor", 50, new int[] {5,10,8,5}, 25, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 4.0F);
	
	public static void createItems() {
		ForgeRegistries.ITEMS.register(upgradedDiamond = new BasicItem("upgraded_diamond"));
		ForgeRegistries.ITEMS.register(obsidianIngot = new BasicItem("obsidian_ingot"));
		ForgeRegistries.ITEMS.register(hybridMix = new BasicItem("hybrid_mix"));
		ForgeRegistries.ITEMS.register(hybridIngot = new BasicItem("hybrid_ingot"));
		ForgeRegistries.ITEMS.register(ironRod = new BasicItem("iron_rod"));
		ForgeRegistries.ITEMS.register(diamondRod = new BasicItem("diamond_rod"));
		ForgeRegistries.ITEMS.register(obsidianRod = new BasicItem("obsidian_rod"));
		ForgeRegistries.ITEMS.register(upgradedDiamondPickaxe = new ItemModPickaxe("upgraded_diamond_pickaxe", UPGRADED_DIAMOND));
		ForgeRegistries.ITEMS.register(upgradedDiamondAxe = new ItemModAxe("upgraded_diamond_axe", UPGRADED_DIAMOND, 8.0F, -2.9F));
		ForgeRegistries.ITEMS.register(upgradedDiamondHoe = new ItemModHoe("upgraded_diamond_hoe", UPGRADED_DIAMOND));
		ForgeRegistries.ITEMS.register(upgradedDiamondShovel = new ItemModSpade("upgraded_diamond_shovel", UPGRADED_DIAMOND));
		ForgeRegistries.ITEMS.register(upgradedDiamondSword = new ItemModSword("upgraded_diamond_sword", UPGRADED_DIAMOND));
		ForgeRegistries.ITEMS.register(emeraldPickaxe = new ItemModPickaxe("emerald_pickaxe", EMERALD));
		ForgeRegistries.ITEMS.register(emeraldAxe = new ItemModAxe("emerald_axe", EMERALD, 8.5F, -2.8F));
		ForgeRegistries.ITEMS.register(emeraldHoe = new ItemModHoe("emerald_hoe", EMERALD));
		ForgeRegistries.ITEMS.register(emeraldShovel = new ItemModSpade("emerald_shovel", EMERALD));
		ForgeRegistries.ITEMS.register(emeraldSword = new ItemModSword("emerald_sword", EMERALD));
		ForgeRegistries.ITEMS.register(obsidianPickaxe = new ItemModPickaxe("obsidian_pickaxe", OBSIDIAN));
		ForgeRegistries.ITEMS.register(obsidianAxe = new ItemModAxe("obsidian_axe", OBSIDIAN, 9.0F, -2.7F));
		ForgeRegistries.ITEMS.register(obsidianHoe = new ItemModHoe("obsidian_hoe", OBSIDIAN));
		ForgeRegistries.ITEMS.register(obsidianShovel = new ItemModSpade("obsidian_shovel", OBSIDIAN));
		ForgeRegistries.ITEMS.register(obsidianSword = new ItemModSword("obsidian_sword", OBSIDIAN));
		ForgeRegistries.ITEMS.register(hybridPickaxe = new ItemModPickaxe("hybrid_pickaxe", HYBRID));
		ForgeRegistries.ITEMS.register(hybridAxe = new ItemModAxe("hybrid_axe", HYBRID, 10.0F, -2.5F));
		ForgeRegistries.ITEMS.register(hybridHoe = new ItemModHoe("hybrid_hoe", HYBRID));
		ForgeRegistries.ITEMS.register(hybridShovel = new ItemModSpade("hybrid_shovel", HYBRID));
		ForgeRegistries.ITEMS.register(hybridSword = new ItemModSword("hybrid_sword", HYBRID));
		ForgeRegistries.ITEMS.register(upgradedDiamondHelmet = new ItemModArmor("upgraded_diamond_helmet", UPGRADED_DIAMONDA, 1, EntityEquipmentSlot.HEAD));
		ForgeRegistries.ITEMS.register(upgradedDiamondChestplate = new ItemModArmor("upgraded_diamond_chestplate", UPGRADED_DIAMONDA, 1, EntityEquipmentSlot.CHEST));
		ForgeRegistries.ITEMS.register(upgradedDiamondLeggings = new ItemModArmor("upgraded_diamond_leggings", UPGRADED_DIAMONDA, 2, EntityEquipmentSlot.LEGS));
		ForgeRegistries.ITEMS.register(upgradedDiamondBoots = new ItemModArmor("upgraded_diamond_boots", UPGRADED_DIAMONDA, 1, EntityEquipmentSlot.FEET));
		ForgeRegistries.ITEMS.register(emeraldHelmet = new ItemModArmor("emerald_helmet", EMERALDA, 1, EntityEquipmentSlot.HEAD));
		ForgeRegistries.ITEMS.register(emeraldChestplate = new ItemModArmor("emerald_chestplate", EMERALDA, 1, EntityEquipmentSlot.CHEST));
		ForgeRegistries.ITEMS.register(emeraldLeggings = new ItemModArmor("emerald_leggings", EMERALDA, 2, EntityEquipmentSlot.LEGS));
		ForgeRegistries.ITEMS.register(emeraldBoots = new ItemModArmor("emerald_boots", EMERALDA, 1, EntityEquipmentSlot.FEET));
		ForgeRegistries.ITEMS.register(obsidianHelmet = new ItemModArmor("obsidian_helmet", OBSIDIANA, 1, EntityEquipmentSlot.HEAD));
		ForgeRegistries.ITEMS.register(obsidianChestplate = new ItemModArmor("obsidian_chestplate", OBSIDIANA, 1, EntityEquipmentSlot.CHEST));
		ForgeRegistries.ITEMS.register(obsidianLeggings = new ItemModArmor("obsidian_leggings", OBSIDIANA, 2, EntityEquipmentSlot.LEGS));
		ForgeRegistries.ITEMS.register(obsidianBoots = new ItemModArmor("obsidian_boots", OBSIDIANA, 1, EntityEquipmentSlot.FEET));
		ForgeRegistries.ITEMS.register(hybridHelmet = new ItemModArmor("hybrid_helmet", HYBRIDA, 1, EntityEquipmentSlot.HEAD));
		ForgeRegistries.ITEMS.register(hybridChestplate = new ItemModArmor("hybrid_chestplate", HYBRIDA, 1, EntityEquipmentSlot.CHEST));
		ForgeRegistries.ITEMS.register(hybridLeggings = new ItemModArmor("hybrid_leggings", HYBRIDA, 2, EntityEquipmentSlot.LEGS));
		ForgeRegistries.ITEMS.register(hybridBoots = new ItemModArmor("hybrid_boots", HYBRIDA, 1, EntityEquipmentSlot.FEET));
	}
}
